### PR TITLE
feat(rotate): now users can apply origin, if necessary

### PR DESCRIPTION
**Pull request by dalisoft**

### CODE REVIEW

**Comment by colinmeinke** [comment]
The code looks good - my only concern is - IS this necessary? Have you had a use case where you needed this?

**Comment by dalisoft** [comment]
Yes i need this usecase when transforming without attributes

**Comment by dalisoft** [comment]
I provide own custom library based on Points.js

**Comment by colinmeinke** [comment]
Not sure what you mean by "transforming without attributes", but I think I will wait until there is more demand for this feature.

**Pull request closed without merging**
