### PR TITLE
feat(autofix): some functions for better/complex shape morphing/interpolating

### PR DESCRIPTION
**Pull request by dalisoft**
* feat(area): gets shape points direction (clockwise, counter-clockwise, collinear)
* feat(autoIndex): matches closer and best index for point by comparing to other shape points
* feat(autoReverse): with using `area` it finds shape points should be reversed or not and automacilly does it for you
* chore(helpers): distance helper function was added

### autoIndex
```javascript
let firstShape = [{x:0,y:0},...]; // Your original from shape
let secondShape = [{x:1,y:1}...]; // Your original to shape
secondShape = autoIndex(secondShape, firstShape[0]);
```

### autoReverse
```javascript
firstShape = autoReverse(firstShape);
```

### distance (at `helpers.js`)
```javascript
let dist = distance(firstShape[0], secondShape[0]); // 359.1934 
```

### area
```javascript
let areaFirstShape = area(firstShape); // -19384, if this number was higher than 0, shape points should be reversed, but you can use autoReverse instead for automatic
```

### CODE REVIEW

**Comment by dalisoft** [comment]
@colinmeinke Can you think about merge or i'm something did wrong? Or you not try to implement these features at all? If you say no, i will close PR and make own fork (publish to npm)

**Comment by colinmeinke** [comment]
Firstly, thanks for you hard work! I like your coding style, it's very readable 😄 

It's always a good idea to open an issue and ask if a PR would be welcomed before you submit one.

My thoughts on auto index are that it is a feature that I would like to add to Wilderness core. I want to keep Points as small as possible.

I was also thinking that it would work something like `autoIndex(shape1, shape2)`. Isn't the point of auto index, to find the best index so a morph between two shapes is as natural as possible? I'm not sure what you are basing your best index on here?

What is the use case for `autoReverse`? Is this so all shapes are drawn in the same direction? If this is the case, I'm not sure this is something that needs to be automated.

I'm going to close this, and I will add auto index to Wilderness core, after I have released Wilderness next.

**Comment by dalisoft** [comment]
Autoreverse will reverse if shape should be reversed. I did some research and inspired from flubber direction reverse for points. About autoIndex. It can be apply for both shapes. Old algorithm based on closest point relative to other shape. But today i am worked full day on it and it worked the boundingBox trick.

**Comment by dalisoft** [comment]
I will making own library and dependecy is points, svg-points. For it i made PR for it. I try to make full-featured morph library with smallest possible size with line drawing, motionPath and etc

**Comment by dalisoft** [comment]
My latest algorithm tries find best index as possible for best natural. But in some shapes need handwork

**Comment by dalisoft** [comment]
I will improve autoReverse and autoIndex for easier for points if you want. Wilderness.js best and fast. But i trying to get lightweight and faster morph library. You can see my repo (minimorph on npm and my profile)

**Comment by dalisoft** [comment]
Points.js is small and module bundler supports tree shaking. I think/sure you know about. Why care about size. It is modular and users load which modules they need

**Comment by dalisoft** [comment]
Here i did some work for shape normalising: https://github.com/dalisoft/points.js

**Comment by colinmeinke** [comment]
It's not just size I'm concerned about, it's about keeping things simple and maintainable, and only implementing features that a.) I understand b.) are absolutely necessary or where there is a lot of demand. As I said, I think Points isn't the place for `autoIndex`, I think that should be done at the level up (i.e. Wilderness, and it is on the road map).

"Autoreverse will reverse if shape should be reversed" - but when should a shape be reversed, I don't understand? What is this based on?

BTW Wilderness Next can be taken for a spin now, https://github.com/colinmeinke/wilderness/tree/next. The only missing feature is timeline events.

**Comment by dalisoft** [comment]
I now maintaining extended version of Points.js as i need that for my future with autoFix function.

**Comment by colinmeinke** [comment]
Sure. Could you explain to be about autoReverse though? What am I missing?

**Comment by dalisoft** [comment]
There some resources that i inspired:
Flubber.js code part, but i did improved: https://github.com/veltman/flubber/blob/master/src/normalize.js#L38

Area function for js: https://github.com/d3/d3-polygon/blob/master/src/area.js and original is http://www.mathopenref.com/coordpolygonarea2.html

**Comment by dalisoft** [comment]
For `autoIndex` i worked full-day with playing of every point and finally get what i need.

**Comment by dalisoft** [comment]
Now i working on my splitting single-path to multi-path like Paper.js does and Flubber.js does

**Comment by dalisoft** [comment]
@colinmeinke See [here](https://codepen.io/dalisoft/pen/vJBBQw), it works with extendeds Points.js, users just need call `autoFix` and hooray. Everything will normalise our js

**Pull request closed without merging**
